/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.trendyol.shoppingcart;

import com.trendyol.shoppingcart.cart.ShoppingCart;
import com.trendyol.shoppingcart.delivery.DeliveryCostCalculator;
import com.trendyol.shoppingcart.discount.campaign.Campaign;
import com.trendyol.shoppingcart.discount.coupon.Coupon;
import com.trendyol.shoppingcart.discount.DiscountType;
import com.trendyol.shoppingcart.product.Category;
import com.trendyol.shoppingcart.product.Product;

public class App {

    public static void main(String[] args) {
        Category food = new Category("food");

        Product apple = new Product("Apple", 100.0, food);
        Product almond = new Product("Almonds", 150.0, food);

        ShoppingCart cart = new ShoppingCart();

        cart.addItem(apple, 3);
        cart.addItem(almond, 1);

        Campaign campaign1 = new Campaign(food, 20.0, 3, DiscountType.RATE);
        Campaign campaign2 = new Campaign(food, 50.0, 1, DiscountType.AMOUNT);

        cart.applyCampaigns(campaign1, campaign2);

        Coupon coupon = new Coupon(100, 10, DiscountType.RATE);

        cart.applyDiscount(coupon);

        DeliveryCostCalculator deliveryCostCalculator = new DeliveryCostCalculator(2, 2, 2.99);
        deliveryCostCalculator.calculateFor(cart);

        cart.print();
    }
}
